In [21]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels)=mnist.load_data()



*   6만개의 훈련이미지, 1만개의 테스트이미지
*   input: 흑백 손글씨 숫자 이미지(28*28 pixel)
*   output: 10개의 범주(0~9)





In [22]:
train_images.shape

(60000, 28, 28)



*   28*28 pixel 로 이루어진 6만개의 훈련(train) 이미지



In [17]:
len(train_images)

60000



*   len: dataset 안의 이미지 개수 확인



In [4]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)



*   6만개의 훈련이미지 각각에 매칭되어 있는 label



In [9]:
test_images.shape

(10000, 28, 28)

In [26]:
# to_categorical 하기 전의 test label
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [25]:
# reshape하기 전의 train image
train_images

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [27]:
train_images=train_images.reshape((60000,28*28))
train_images=train_images.astype('float32')/255

test_images=test_images.reshape((10000,28*28))
test_images=test_images.astype('float32')/255

In [20]:
# reshape 하고 나서의 train image
train_images

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [28]:
from keras.utils import to_categorical

train_labels=to_categorical(train_labels)
test_labels=to_categorical(test_labels)

In [29]:
#categorical 하고 나서의 test label
test_labels

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [10]:
from keras import models
from keras import layers

network=models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
network.add(layers.Dense(10, activation='softmax'))

layers.Dense(10, activation='softmax')

→해당 숫자 이미지가 10개의 숫자 클래스 중 하나에 속할 확률이 총 10개 들어 있다.(모두 더하면 1)

In [12]:
network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

In [31]:
network.fit(train_images,train_labels,epochs=5,batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 5s 82us/step - loss: 0.2550 - accuracy: 0.9259
Epoch 2/5
60000/60000 [==============================] - 5s 79us/step - loss: 0.1053 - accuracy: 0.9691
Epoch 3/5
60000/60000 [==============================] - 5s 78us/step - loss: 0.0686 - accuracy: 0.9793
Epoch 4/5
60000/60000 [==============================] - 5s 78us/step - loss: 0.0506 - accuracy: 0.9847
Epoch 5/5
60000/60000 [==============================] - 5s 78us/step - loss: 0.0375 - accuracy: 0.9888


In [32]:
test_loss, test_acc=network.evaluate(test_images, test_labels)
print('test_loss: ',test_loss)
print('test_acc: ', test_acc)

10000/10000 [==============================] - 1s 59us/step
test_loss:  0.06370544586420292
test_acc:  0.980400025844574


테스트 셋(test)에 대한 정확도가 훈련 셋(train)에 대한 정확도 보다 약간 낮은 것을 확인 할 수 있다.

*   과대적합(overfitting): 훈련 데이터보다 새로운 데이터에서 성능이 낮아지는 경향을 가리킨다.

